### ISSUE TITLE
Response length limit for technical evaluation

### ISSUE THREAD

**Issue by reedloden** [18F/tts-buy-bug-bounty#18]
# Question/Comment on TTS Bug Bounty RFQ

## Name and affiliation
Reed Loden
Director of Security
HackerOne, Inc.

## Section of RFQ documents
RFQ
5.1 - Phase 1 Technical Evaluation
https://github.com/18F/tts-buy-bug-bounty/blob/d6dcb9f669d4da26ed1488dd275e3325bbbbc729/2018-procurement/RFQ.md#51---phase-1-technical-evaluation

## Question/Comment
Is there a response length limit for the technical evaluation?

**Comment by MichelleMcNellis** [comment]
Please see Issue #31 response. https://github.com/18F/tts-buy-bug-bounty/issues/32
