### ISSUE TITLE
Where to submit responses to questions for potential vendors

### ISSUE THREAD

**Issue by reedloden** [18F/tts-buy-bug-bounty#5]
# Question/Comment on TTS Bug Bounty draft RFO

## Name and affiliation
Reed Loden
Director of Security
HackerOne, Inc.

## Section of RFO documents
Non-Applicable: Guideline to submit responses to questions for potential vendors.

## Question/Comment
Should we submit answers to the questions to potential vendors in an issue via GitHub (due date 01/30) or to the provided email address to the TTS contracting officer?

**Comment by MichelleMcNellis** [comment]
Please submit questions via email to the contracting officer, michelle.mcnellis@gsa.gov.

**Comment by reedloden** [comment]
Thanks!
