### ISSUE TITLE
Elaborate on "all costs paid directly to the researchers"

### ISSUE THREAD

**Issue by reedloden** [18F/tts-buy-bug-bounty#6]
# Question/Comment on TTS Bug Bounty draft RFO

## Name and affiliation
Reed Loden
Director of Security
HackerOne, Inc.

## Section of RFO documents
Section 4.0 Type of Contract

## Question/Comment
Can you please elaborate on what you mean by "all costs paid directly to the researchers"?

**Comment by MichelleMcNellis** [comment]
The bounty pool funds 100% represent rewards -- money paid out as bounties. Fees associated with this contract should be represented within other CLINs, if applicable.
