### ISSUE TITLE
RFO response deadline

### ISSUE THREAD

**Issue by reedloden** [18F/tts-buy-bug-bounty#7]
# Question/Comment on TTS Bug Bounty draft RFO

## Name and affiliation
Reed Loden
Director of Security
HackerOne, Inc.

## Section of RFO documents
N/A

## Question/Comment
When do we need to submit the response to the RFO by? No possible date is mentioned, but any estimates on a deadline would be helpful for planning purposes.

**Comment by MichelleMcNellis** [comment]
This was a draft solicitation for planning purposes ONLY. This request is NOT a solicitation. Please do NOT submit a proposal. The questions that were asked, the responses were due today, January 30,2017 at 4pm.

**Comment by reedloden** [comment]
We understand that. We just want to know that if this does become a solicitation at some point, what might a future timeline be? :)
