### ISSUE TITLE
Performance requirements

### ISSUE THREAD

**Issue by reedloden** [18F/tts-buy-bug-bounty#8]
# Question/Comment on TTS Bug Bounty draft RFO

## Name and affiliation
Reed Loden
Director of Security
HackerOne, Inc.

## Section of RFO documents
Section 2.1 Performance Requirements Matrix

## Question/Comment
Are the three listed performance requirements the full and complete list, or will TTS add more later?

**Comment by MichelleMcNellis** [comment]
At this time, for the draft solicitation it is the complete list.
